#ifndef MAP_INDEX_H
#define MAP_INDEX_H
#include <types.h>

typedef enum MapIndex
{
#if !defined(BUILD_PS2)
    MI_Map_Loading,
    MI_LoadingLoop_2D,
#endif
    MI_MR1_Blk,
    MI_MR1_Sgt,
    MI_MR1_Spx,
    MI_MR1_Spy,
    MI_MR2_Blk,
    MI_MR2_Sgt,
    MI_MR2_Spx,
    MI_MR2_Spy,
    MI_MR3_Blk,
    MI_MR3_Sgt,
    MI_MR3_Spx,
    MI_MR3_Spy,
    MI_MR4_Blk,
    MI_MR4_Sgt,
    MI_MR4_Spx,
    MI_MR4_Spy,
    MI_Credits,
    MI_SunkenRuins,
    MI_CloudyDomain,
    MI_CloudyDomainBallGadget,
    MI_DragonflyFalls,
    MI_CrocovileSwamp,
    MI_DragonVillage,
    MI_R1LinkAB,
    MI_R1LinkAC,
    MI_Example,
    MI_Test_DP,
    MI_MorphEnv,
    MI_DarkMine,
    MI_FrostbiteVillage,
    MI_GnastysCave,
    MI_IceCitadel,
    MI_RedsLair,
    MI_GloomyGlacier,
    MI_Playroom,
    MI_ModelViewer,
    MI_Test_TL,
    MI_Test_PB,
    MI_RedsLaboratory,
    MI_RedsChamber,
    MI_Test_MF,
    MI_Shop,
    MI_StormyBeach,
    MI_CoastalRemains,
    MI_R2LinkAB,
    MI_R2LinkAC,
    MI_Test_JS,
    MI_Test_KA,
    MI_Test_NB,
    MI_Test_NB2,
    MI_Test_SJ,
    MI_PlatformArea,
    MI_TestBeach,
    MI_TestBall,
    MI_Titles,
    MI_R4LinkBC,
    MI_R4LinkCD,
    MI_R4LinkDE,
    MI_MoltenMount,
    MI_MagmaFallsTop,
    MI_MagmaFallsBallGadget,
    MI_MagmaFallsBottom,
    MI_WateryTomb
} MapIndex;

#endif /* MAP_INDEX_H */