#include <ap_objectives.h>
#include <types.h>
#include <hashcodes.h>

EXHashCode new_game_objectives[] = {
    // Realm introduction cutscenes
    HT_Objective_OpeningMovie,
    HT_Objective_SeenIntro_R1A,
    HT_Objective_SeenIntroR2A,
    HT_Objective_SeenProfStartR2A,
    HT_Objective_SeenIntroR3A,
    HT_Objective_SeenProfStartR3A,
    HT_Objective_SeenIntroR4A,
    HT_Objective_ProfGoneToFindRed,

    // Opened starting gate
    HT_Objective_R1A_OpenLockPickerSwitch,
    
    // Zoe intro cutscene
    HT_Objective_R1A_MetZoe,

    // Met the mammoth and rescued Spyro.
    // This is to prevent the gate into Gloomy Glacier from being present,
    // and to allow access to Gloomy Glacier at the player's discretion.
    HT_Objective_3A_MetMonsterMammoth,
    HT_Objective_3B_HunterRescuedSpyro,

    // Moneybags intro
    HT_Objective_MoneybagsGems_1A,
    HT_Objective_Moneybagsintro_1A,
    HT_Objective_GainedLockPicker,

    // Remote shop pad intro
    HT_Objective_1A_DoneHoloMBChat,

    // Pop-ups
    HT_Objective_PopUp_1AChSwitch,
    HT_Objective_PopUP_1AHDSwitch,
    HT_Objective_PopUp1B_Spinpole,
    HT_Objective_PopUp_1C_Cannon,
    HT_Objective_PopUp_1A_WeightSwitch,
    HT_Objective_PopUP_1A_Lock_PickerGate,
    HT_Objective_PopUp_1A_Ledges,
    HT_Objective_PopUp_1A_WickerVases,
    HT_Objective_PopUp_1A_MetalChests,
    HT_Objective_PopUp_1A_DoubleJumpLedges,
    HT_Objective_PopUp_1A_HDChests,
    HT_Objective_PopUp_1AGnorc,
    HT_Objective_PopUp_1ALightGrm,
    HT_Objective_PopUp_1ADragonEgg,
    HT_Objective_PopUp_1ABoss,
    HT_Objective_PopUp_1C_Hunter_DJumpLedges,
    HT_Objective_PopUp_1C_Hunter_UsingTheBow,
    HT_Objective_PopUp_1C_Hunter_DashPunch,
    HT_Objective_PopUp_1C_Hunter_JumpBowAttack,
    HT_Objective_PopUp_1C_Hunter_StompMove,
    HT_Objective_PopUp_1C_Hunter_FirstPersonAim,
    HT_Objective_PopUp_1C_Hunter_BowDeflector,
    HT_Objective_PopUp_1C_Hunter_WallClimb,
    HT_Objective_PopUp_1C_Hunter_Fodder,
    HT_Objective_PopUp_1C_Hunter_CautiousWalk,
    HT_Objective_PopUp_1C_Hunter_SecondaryFire,
    HT_Objective_PopUp_1C_Hunter_FirstPersonReminder,
    HT_Objective_PopUp_1AFireBreath,
    HT_Objective_PopUp_1C_Hunter_FlyingKick,
    HT_Objective_PopUp_1C_Hunter_HoldingAttack,
    HT_Objective_PopUp_1C_Hunter_ExplosiveArrows,
    HT_Objective_PopUp_1C_SgtByrd_BasicThrusting,
    HT_Objective_PopUp_1C_SgtByrd_BombTargets,
    HT_Objective_PopUp_1C_SgtByrd_Missiles,
    HT_Objective_PopUp_1C_SgtByrd_BoosterFuel,
    HT_Objective_PopUp_1A_TempMoneybags,
    HT_Objective_PopUp_1A_FirstPersonView,
    HT_Objective_PopUp_1A_SparxHealth,
    HT_Objective_PopUp_1A_FodderSheep,
    HT_Objective_PopUp_1A_CameraControls,
    HT_Objective_PopUp_1A_HudInfo,
    HT_Objective_PopUp_1A_DarkGemShards,
    HT_Objective_PopUp_1C_SgtByrd_Tallies,
    HT_Objective_PopUp_1AGnorcArmored,
    HT_Objective_PopUp_1C_SgtByrd_TimeGates,
    HT_Objective_PopUp_1B_Blink_UseBlaster,
    HT_Objective_PopUp_1B_Blink_DashPunch,
    HT_Objective_PopUp_1B_Blink_ClawingDigging,
    HT_Objective_PopUp_1B_Blink_BombDispenser,
    HT_Objective_PopUp_1B_Blink_ThrowingBombs,
    HT_Objective_PopUp_1B_Blink_WallCling,
    HT_Objective_PopUp_1B_Blink_CeilingCling,
    HT_Objective_PopUp_1B_Blink_Stomp,
    HT_Objective_PopUp_1A_StrongChest,
    HT_Objective_PopUp_1A_LockedChest,
    HT_Objective_PopUp_1A_Fireworks,
    HT_Objective_PopUp_1A_BossBarrier,
    HT_Objective_PopUp_1B_Turret_Tallies,
    HT_Objective_PopUp_1B_Turret_Firing,
    HT_Objective_PopUp_1B_Turret_Target,
    HT_Objective_PopUp_1B_Turret_Progress,
    HT_Objective_PopUp_1B_Turret_Radar,
    HT_Objective_PopUp_1C_Sparx_Tallies,
    HT_Objective_PopUp_1C_Sparx_BasicFire,
    HT_Objective_PopUp_1C_Sparx_Missiles,
    HT_Objective_PopUp_1C_Sparx_SmartBomb,
    HT_Objective_PopUp_1C_Sparx_Brake,
    HT_Objective_PopUp_1C_Sparx_Boost,
    HT_Objective_PopUp_1B_Blink_Tallies,
    HT_Objective_PopUp_1C_SecretDoor,
    HT_Objective_PopUp_2A_SecretDoor,
    HT_Objective_PopUp_3A_SecretDoor,
    HT_Objective_PopUp_4D_SecretDoor,
    HT_Objective_PopUp_1A1C_Ball_BasicRolling,
    HT_Objective_PopUp_1A1C_Ball_Jump,
    HT_Objective_PopUp_1A1C_Ball_Brake,
    HT_Objective_PopUp_1A1C_Ball_Boost,
    HT_Objective_Popup_SpinPoleUse,
    HT_Objective_PopUp_General_ElectricBreath,
    HT_Objective_PopUp_General_WaterBreath,
    HT_Objective_PopUp_General_IceBreath,
    HT_Objective_PopUp_General_ElectricBreathSelection,
    HT_Objective_PopUp_General_WaterBreathSelection,		
    HT_Objective_PopUp_General_IceBreathSelection,		
    HT_Objective_PopUp_General_AtlasAccess,
    HT_Objective_PopUp_General_HelpScreen,
    HT_Objective_PopUp_General_StrongDoors,
    HT_Objective_PopUp_General_Thermals,
    HT_Objective_PopUp_General_WallKickNotGot,
    HT_Objective_PopUp_General_WallKickGot,
    HT_Objective_PopUp_General_WingShieldGot,
    HT_Objective_PopUp_General_IceSurface,
    HT_Objective_PopUp_General_TNTCrates,
    HT_Objective_PopUp_2A_BossBarrier,
    HT_Objective_PopUp_3A_BossBarrier,
    HT_Objective_PopUp_4E_BossBarrier,
    HT_Objective_PopUp_3A_IceSurface,
    HT_Objective_PopUp_1B_Blink_BlinkoVision,
    HT_Objective_PopUp_1B_Blink_Defense,
    HT_Objective_PopUp_General_TaskList,
    HT_Objective_PopUp_General_Swimming,
    HT_Objective_PopUp_General_EggThief,
    HT_Objective_PopUp_General_Talking,
    HT_Objective_PopUp_1B_Blink_DoubleJump,
    HT_Objective_PopUp_1C_Sparx_RapidFire,
    HT_Objective_OpenSwimming
};